name: first_machine_learning
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  tflite: ^1.1.2
  camera: ^0.10.5+5
  image: ^4.1.3
  path_provider: ^2.1.1

dev_dependencies: 
  flutter_lints: 2.0.3
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

